# Users schema

# --- !Ups
CREATE TABLE SENDLOGS (
	ID	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	USERNAME	REAL NOT NULL,
	SENDER	TEXT NOT NULL,
	DESTINATION	TEXT NOT NULL,
	MESSAGE	TEXT NOT NULL,
	SENDTIME	INTEGER NOT NULL
);

# --- !Downs
DROP TABLE SENDLOGS;